@echo off
REM Generate app.conf by scanning the Maven project (parent of this folder).
REM Usage: init-app-conf.bat [--force]
setlocal EnableExtensions EnableDelayedExpansion

set "PACK_DIR=%~dp0"
if "%PACK_DIR:~-1%"=="\" set "PACK_DIR=%PACK_DIR:~0,-1%"
for %%I in ("%PACK_DIR%\..") do set "ROOT=%%~fI"
set "CONF=%PACK_DIR%\app.conf"
set "FORCE=0"
if /i "%~1"=="--force" set "FORCE=1"
if /i "%~1"=="-f" set "FORCE=1"

if exist "%CONF%" if "%FORCE%"=="0" (
  echo Already exists: %CONF%
  echo Use --force to overwrite, or edit then run pack.bat
  exit /b 1
)

if not exist "%ROOT%\pom.xml" (
  echo No pom.xml in %ROOT%
  echo Put this folder next to pom.xml under the Maven project root.
  exit /b 1
)

where mvn >nul 2>&1
if errorlevel 1 (
  echo Missing mvn in PATH
  exit /b 1
)

echo ==^> detect %ROOT%

for /f "usebackq delims=" %%v in (`mvn -q -DforceStdout help:evaluate -Dexpression=project.artifactId -f "%ROOT%\pom.xml" 2^>nul`) do set "ART=%%v"
for /f "usebackq delims=" %%v in (`mvn -q -DforceStdout help:evaluate -Dexpression=project.version -f "%ROOT%\pom.xml" 2^>nul`) do set "VERSION=%%v"
for /f "usebackq delims=" %%v in (`mvn -q -DforceStdout help:evaluate -Dexpression=project.name -f "%ROOT%\pom.xml" 2^>nul`) do set "APP_NAME=%%v"
for /f "usebackq delims=" %%v in (`mvn -q -DforceStdout help:evaluate -Dexpression=project.groupId -f "%ROOT%\pom.xml" 2^>nul`) do set "VENDOR=%%v"
for /f "usebackq delims=" %%v in (`mvn -q -DforceStdout help:evaluate -Dexpression=project.description -f "%ROOT%\pom.xml" 2^>nul`) do set "APP_DESCRIPTION=%%v"
for /f "usebackq delims=" %%v in (`mvn -q -DforceStdout help:evaluate -Dexpression=project.build.finalName -f "%ROOT%\pom.xml" 2^>nul`) do set "FINAL=%%v"
for /f "usebackq delims=" %%v in (`mvn -q -DforceStdout help:evaluate -Dexpression=main.class -f "%ROOT%\pom.xml" 2^>nul`) do set "MAIN_CLASS=%%v"

if not defined APP_NAME set "APP_NAME=%ART%"
if defined APP_NAME set "APP_NAME=%APP_NAME: =%"
if not defined APP_NAME set "APP_NAME=MyApp"
if not defined VENDOR set "VENDOR=%APP_NAME%"
if not defined APP_DESCRIPTION set "APP_DESCRIPTION=%APP_NAME%"
if defined FINAL (
  set "MAVEN_JAR=target\%FINAL%.jar"
) else if defined ART if defined VERSION (
  set "MAVEN_JAR=target\%ART%-%VERSION%.jar"
) else (
  set "MAVEN_JAR=target\%APP_NAME%.jar"
)
set "MAVEN_JAR=%MAVEN_JAR:\=/%"

set "LINUX_PKG_NAME=%APP_NAME%"
powershell -NoProfile -Command "$n='%APP_NAME%'.ToLower() -replace '[^a-z0-9+.-]',''; Write-Output $n" > "%TEMP%\pack_linux_pkg.txt"
set /p LINUX_PKG_NAME=<"%TEMP%\pack_linux_pkg.txt"

set "JP_MODULES=java.base,java.desktop,java.datatransfer,java.prefs,jdk.charsets"
findstr /i /c:"org.openjfx" "%ROOT%\pom.xml" >nul 2>&1
if not errorlevel 1 set "JP_MODULES=java.base,java.desktop,java.datatransfer,java.prefs,jdk.charsets,javafx.base,javafx.graphics,javafx.controls,javafx.fxml"

set "MAVEN_EXTRA_ARGS="
findstr /i /c:"<id>all-natives</id>" "%ROOT%\pom.xml" >nul 2>&1
if not errorlevel 1 set "MAVEN_EXTRA_ARGS=-P all-natives"

set "ICON_PNG=other/icon.png"
set "ICON_ICO=other/icon.ico"
set "ICON_ICNS=other/icon.icns"
if exist "%ROOT%\src\main\resources\resources\icon.png" set "ICON_PNG=src/main/resources/resources/icon.png"
if exist "%ROOT%\src\main\resources\icon.png" set "ICON_PNG=src/main/resources/icon.png"
if exist "%ROOT%\other\icon.ico" set "ICON_ICO=other/icon.ico"
if exist "%ROOT%\other\icon.icns" set "ICON_ICNS=other/icon.icns"

set "VERSION_JAVA="

(
echo # Generated by init-app-conf.bat. No spaces around =. Paths relative to project root.
echo # Required: APP_NAME / MAIN_CLASS / MAVEN_JAR
echo.
echo APP_NAME=%APP_NAME%
echo MAIN_CLASS=%MAIN_CLASS%
echo MAVEN_JAR=%MAVEN_JAR%
echo.
echo VENDOR=%VENDOR%
echo APP_DESCRIPTION=%APP_DESCRIPTION%
echo VERSION=%VERSION%
echo VERSION_JAVA=%VERSION_JAVA%
echo LINUX_PKG_NAME=%LINUX_PKG_NAME%
echo.
echo ICON_PNG=%ICON_PNG%
echo ICON_ICO=%ICON_ICO%
echo ICON_ICNS=%ICON_ICNS%
echo.
echo JP_MODULES=%JP_MODULES%
echo JAVAFX_JMODS=
echo MAVEN_EXTRA_ARGS=%MAVEN_EXTRA_ARGS%
echo JAVA_OPTIONS=-Dfile.encoding=UTF-8
echo MENU_GROUP=Utility
) > "%CONF%"

echo Wrote %CONF%
echo APP_NAME=%APP_NAME%
echo MAIN_CLASS=%MAIN_CLASS%
echo MAVEN_JAR=%MAVEN_JAR%
echo VERSION=%VERSION%
echo JP_MODULES=%JP_MODULES%
if not defined MAIN_CLASS (
  echo MAIN_CLASS is empty - edit app.conf
  exit /b 1
)
echo Next: pack.bat
endlocal
