REM 用于安装TightVNC
@echo off&color 17
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (goto UACPrompt) else (goto UACAdmin)
:UACPrompt
%1 start "" mshta vbscript:createobject("shell.application").shellexecute("""%~0""","::",,"runas",1)(window.close)&exit
exit /B
:UACAdmin
cd /d "%~dp0"
::echo 当前运行路径是：%CD%
echo 已获取管理员权限。。。
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo install TightVNC
echo.
echo.
echo.
echo.
echo.
echo.
msiexec.exe /i tightvnc.msi /quiet /norestart
SET_USEVNCAUTHENTICATION=1
VALUE_OF_USEVNCAUTHENTICATION=1
SET_PASSWORD=1
VALUE_OF_PASSWORD=mainpass
SET_VIEWONLYPASSWORD=1
VALUE_OF_VIEWONLYPASSWORD=viewpass
SET_USECONTROLAUTHENTICATION=1
VALUE_OF_USECONTROLAUTHENTICATION=1
SET_CONTROLPASSWORD=1
VALUE_OF_CONTROLPASSWORD=admpass
echo.
echo INSTALLING AND CONFIGURING ... ... ... .. . .
REM VIEWER_ASSOCIATE_VNC_EXTENSION=0 客户端扩展名关联
REM SERVER_REGISTER_AS_SERVICE=0 服务端扩展名关联
REM SERVER_ADD_FIREWALL_EXCEPTION=1 添加服务端防火墙规则
REM VIEWER_ADD_FIREWALL_EXCEPTION=1 添加客户端防火墙规则
REM SERVER_ALLOW_SAS=1 SET_USEVNCAUTHENTICATION=1  允许”Ctrl+Alt+Del“
REM SET_ACCEPTRFBCONNECTIONS=1 VALUE_OF_ACCEPTRFBCONNECTIONS=0 关闭Web Server
REM SET_DISCONNECTACTION=1 VALUE_OF_DISCONNECTACTION=1 (当断开连接的时候 0 Nothing 1锁屏 2登出)
REM SET_REMOVEWALLPAPER=1 VALUE_OF_REMOVEWALLPAPER=0 (显示远程壁纸)
REM SET_RFBPORT=1 VALUE_OF_RFBPORT=5900 (远程端口)
REM SET_RUNCONTROLINTERFACE=1 VALUE_OF_RUNCONTROLINTERFACE=0 (不显示在系统托盘)
REM 密码相关：
SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1
REM VALUE_OF_USEVNCAUTHENTICATION=1 
REM SET_PASSWORD=1
REM VALUE_OF_PASSWORD=c0nn3cT.
REM SET_USECONTROLAUTHENTICATION=1
REM VALUE_OF_USECONTROLAUTHENTICATION=1
REM SET_CONTROLPASSWORD=1
REM VALUE_OF_CONTROLPASSWORD=C0nTr0l.
msiexec /i tightvnc.msi /quiet /norestart ADDLOCAL="Server,Viewer" VIEWER_ASSOCIATE_VNC_EXTENSION=0 SERVER_REGISTER_AS_SERVICE=0 SERVER_ADD_FIREWALL_EXCEPTION=1 VIEWER_ADD_FIREWALL_EXCEPTION=1 SERVER_ALLOW_SAS=1 SET_REMOVEWALLPAPER=1 VALUE_OF_REMOVEWALLPAPER=0 SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=c0nn3cT. SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=C0nTr0l.
echo.
echo.
echo.
echo.
echo FINISHED!

pause

