@echo off
chcp 65001 >nul
REM TightVNC 高级部署：MSI 装成 Windows 服务，并按 conf\tightvnc.conf 设密码/托盘
color 17
if exist "%SystemRoot%\SysWOW64" path %path%;%windir%\SysNative;%SystemRoot%\SysWOW64;%~dp0
bcdedit >nul
if '%errorlevel%' NEQ '0' (goto UACPrompt) else (goto UACAdmin)
:UACPrompt
%1 start "" mshta vbscript:createobject("shell.application").shellexecute("""%~0""","::",,"runas",1)(window.close)&exit
exit /B
:UACAdmin
for %%I in ("%~dp0..\..") do set "PNAT_ROOT=%%~fI"
cd /d "%PNAT_ROOT%"

echo 包根: %CD%
echo 正在安装并配置 TightVNC（系统服务）
echo INSTALLING AND CONFIGURING ...

REM VIEWER_ASSOCIATE_VNC_EXTENSION=0  不关联 .vnc 文件
REM SERVER_REGISTER_AS_SERVICE=1      注册为 Windows 服务
REM SERVER_ADD_FIREWALL_EXCEPTION=1   服务端防火墙例外
REM VIEWER_ADD_FIREWALL_EXCEPTION=1   查看器防火墙例外
REM SERVER_ALLOW_SAS=1                允许发送 Ctrl+Alt+Del
REM SET_REMOVEWALLPAPER               是否去掉墙纸
REM SET_RUNCONTROLINTERFACE=0         不显示托盘控制界面
REM SET_CONTROLPASSWORD               控制面板密码
REM SET_PASSWORD                      连接密码
REM SET_VIEWONLYPASSWORD              只看密码

copy /y conf\tightvnc.conf tmpScript.bat >nul 2>nul
CALL tmpScript.bat

echo 控制密码: %ctrl_passwd%
echo VNC 密码: %vnc_passwd%
echo 只看密码: %viewonly_passwd%
echo 隐藏托盘: %hide_systray%
echo 5 秒后开始安装...
TIMEOUT /T 5

if "%install_to%"=="" (
echo 未指定安装路径，使用 MSI 默认位置
if %hide_systray% EQU 1 (
echo 隐藏托盘
msiexec /i res\windows\TightVNC\tightvnc.msi /quiet /norestart ADDLOCAL="Server,Viewer" VIEWER_ASSOCIATE_VNC_EXTENSION=0 SERVER_REGISTER_AS_SERVICE=1 SERVER_ADD_FIREWALL_EXCEPTION=1 VIEWER_ADD_FIREWALL_EXCEPTION=1 SERVER_ALLOW_SAS=1 SET_REMOVEWALLPAPER=1 VALUE_OF_REMOVEWALLPAPER=0 SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=%ctrl_passwd% SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=%vnc_passwd% SET_VIEWONLYPASSWORD=1 VALUE_OF_VIEWONLYPASSWORD=%viewonly_passwd% SET_RUNCONTROLINTERFACE=1 VALUE_OF_RUNCONTROLINTERFACE=0
) else (
echo 显示托盘
msiexec /i res\windows\TightVNC\tightvnc.msi /quiet /norestart ADDLOCAL="Server,Viewer" VIEWER_ASSOCIATE_VNC_EXTENSION=0 SERVER_REGISTER_AS_SERVICE=1 SERVER_ADD_FIREWALL_EXCEPTION=1 VIEWER_ADD_FIREWALL_EXCEPTION=1 SERVER_ALLOW_SAS=1 SET_REMOVEWALLPAPER=1 VALUE_OF_REMOVEWALLPAPER=0 SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=%ctrl_passwd% SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=%vnc_passwd% SET_VIEWONLYPASSWORD=1 VALUE_OF_VIEWONLYPASSWORD=%viewonly_passwd%
)
) else (
echo 安装到: %install_to%
if %hide_systray% EQU 1 (
echo 隐藏托盘
msiexec /i res\windows\TightVNC\tightvnc.msi INSTALLDIR=%install_to% TARGETDIR=%install_to% /quiet /norestart ADDLOCAL="Server,Viewer" VIEWER_ASSOCIATE_VNC_EXTENSION=0 SERVER_REGISTER_AS_SERVICE=1 SERVER_ADD_FIREWALL_EXCEPTION=1 VIEWER_ADD_FIREWALL_EXCEPTION=1 SERVER_ALLOW_SAS=1 SET_REMOVEWALLPAPER=1 VALUE_OF_REMOVEWALLPAPER=0 SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=%ctrl_passwd% SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=%vnc_passwd% SET_VIEWONLYPASSWORD=1 VALUE_OF_VIEWONLYPASSWORD=%viewonly_passwd% SET_RUNCONTROLINTERFACE=1 VALUE_OF_RUNCONTROLINTERFACE=0
) else (
echo 显示托盘
msiexec /i res\windows\TightVNC\tightvnc.msi INSTALLDIR=%install_to% TARGETDIR=%install_to% /quiet /norestart ADDLOCAL="Server,Viewer" VIEWER_ASSOCIATE_VNC_EXTENSION=0 SERVER_REGISTER_AS_SERVICE=1 SERVER_ADD_FIREWALL_EXCEPTION=1 VIEWER_ADD_FIREWALL_EXCEPTION=1 SERVER_ALLOW_SAS=1 SET_REMOVEWALLPAPER=1 VALUE_OF_REMOVEWALLPAPER=0 SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=%ctrl_passwd% SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=%vnc_passwd% SET_VIEWONLYPASSWORD=1 VALUE_OF_VIEWONLYPASSWORD=%viewonly_passwd%
)
)

echo FINISHED!
