#!/usr/bin/python3
# Dayon Linux 一键接入 / 保留 / 干净卸载
#
# 原则：
# - 不解压到 /tmp 乱放、不写桌面快捷方式、不碰用户 ~/.dayon
# - 运行时全部落在项目 .runtime/dayon/（可保留复用，或一次卸干净）
# - 用 -Duser.home 把 Dayon 的 .dayon 关进隔离目录

import argparse
import os
import signal
import subprocess
import sys
import time

_LIB = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "lib"))
if _LIB not in sys.path:
    sys.path.insert(0, _LIB)
from lib_paths import abs_under, ensure_import_path, res_dir, runtime_dir
import lib_loadConf as loadConf

ROOT = ensure_import_path(os.path.dirname(os.path.abspath(__file__)))
CONF_PREFIX = "app"
ARCHIVE = os.path.join(res_dir(ROOT), "linux", "Dayon", "dayon.sh")
RUNTIME_ROOT = os.path.join(runtime_dir(ROOT), "dayon")
APP_DIR = os.path.join(RUNTIME_ROOT, "app")
HOME_DIR = os.path.join(RUNTIME_ROOT, "home")
DAYON_HOME = os.path.join(HOME_DIR, ".dayon")
MARKER = os.path.join(RUNTIME_ROOT, ".owned_by_p_nat_setup")

Windows = os.path.sep == "\\"


def project_root():
    return ROOT


def abs_under_root(*parts):
    return abs_under(ROOT, *parts)


def read_conf():
    """读取 GUI/CLI 共用的 conf/app.conf"""
    return loadConf.read_app_conf(ROOT)


def ensure_linux():
    if Windows:
        print("当前脚本先只支持 Linux。Windows 用 res/windows/Dayon/*.exe，后续再接。")
        sys.exit(1)


def ensure_display():
    if not os.environ.get("DISPLAY"):
        print("未检测到 DISPLAY，Dayon 需要图形界面。可先: export DISPLAY=:0")
        sys.exit(1)


def write_marker():
    os.makedirs(abs_under_root(RUNTIME_ROOT), exist_ok=True)
    with open(abs_under_root(MARKER), "w", encoding="utf-8") as f:
        f.write("P_NAT_SETUP dayon runtime\n")


def is_extracted():
    return os.path.isfile(abs_under_root(APP_DIR, "dayon.jar")) and os.path.isfile(
        abs_under_root(APP_DIR, "jrex", "bin", "java")
    )


def extract_app():
    """静默解压 Makeself 到 .runtime/dayon/app，不执行内嵌脚本、不写系统目录。"""
    archive = abs_under_root(ARCHIVE)
    if not os.path.isfile(archive):
        print("找不到 Dayon 包: {}".format(archive))
        sys.exit(1)
    if not os.access(archive, os.X_OK):
        os.chmod(archive, 0o755)

    app = abs_under_root(APP_DIR)
    os.makedirs(app, exist_ok=True)
    write_marker()

    if is_extracted():
        print("已解压，跳过: {}".format(app))
        return

    print("解压 Dayon -> {}".format(app))
    cmd = [
        archive,
        "--target",
        app,
        "--keep",
        "--noexec",
        "--quiet",
        "--noprogress",
        "--nox11",
    ]
    r = subprocess.run(cmd, cwd=project_root())
    if r.returncode != 0 or not is_extracted():
        print("解压失败 (code={})".format(r.returncode))
        sys.exit(1)
    # 确保自带 jre / 脚本可执行
    java = abs_under_root(APP_DIR, "jrex", "bin", "java")
    if os.path.isfile(java):
        os.chmod(java, 0o755)
    print("解压完成")


def write_assisted_yaml(host, port):
    """写到 jar 同目录：Dayon 会读，启动即连，小白无感。"""
    path = abs_under_root(APP_DIR, "assisted.yaml")
    content = (
        'host: "{}"\n'
        "port: {}\n"
        "autoConnect: true\n"
    ).format(host, port)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("写入 {}".format(path))


def write_assistant_prefs(port, auto_accept):
    """隔离 home 下的 preferences；autoAccept 无 CLI，只能预写 properties。"""
    os.makedirs(abs_under_root(DAYON_HOME), exist_ok=True)
    path = abs_under_root(DAYON_HOME, "dayon_assistant.properties")
    aa = "true" if str(auto_accept) in ("1", "true", "True", "yes") else "false"
    content = (
        "# generated by P_NAT_SETUP — do not put this in ~/.dayon\n"
        "assistant.network.portNumber={}\n"
        "assistant.network.autoAccept={}\n"
        "assistant.network.tokenServerUrl=\n"
        "assistant.network.version=1\n"
        "assistant.language=zh\n"
        "assistant.version=1\n"
    ).format(port, aa)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    # 空 yaml 也可放 jar 旁，避免误用用户目录配置
    yaml_path = abs_under_root(APP_DIR, "assistant.yaml")
    with open(yaml_path, "w", encoding="utf-8") as f:
        f.write("# managed by P_NAT_SETUP\n")
    print("写入 {} (autoAccept={})".format(path, aa))


def java_bin():
    return abs_under_root(APP_DIR, "jrex", "bin", "java")


def build_cmd(role, host, port):
    jar = abs_under_root(APP_DIR, "dayon.jar")
    home = abs_under_root(HOME_DIR)
    xmx = "-Xmx512m" if role == "assistant" else "-Xmx1g"
    cmd = [
        java_bin(),
        xmx,
        "-Duser.home={}".format(home),
        "-Ddayon.log=file",
        "-jar",
        jar,
    ]
    if role == "assistant":
        cmd.append("assistant")
    else:
        # CLI 优先，yaml 兜底
        cmd.append("ah={}".format(host))
        cmd.append("ap={}".format(port))
    return cmd


def list_our_pids():
    """只匹配命令行里带本项目 .runtime/dayon 的进程，避免误杀系统其它 Java。"""
    needle = abs_under_root(APP_DIR, "dayon.jar")
    pids = []
    try:
        out = subprocess.check_output(["ps", "-eo", "pid,args"], text=True, errors="ignore")
    except Exception as e:
        print(e)
        return pids
    for line in out.splitlines():
        line = line.strip()
        if not line:
            continue
        if needle not in line and abs_under_root(RUNTIME_ROOT) not in line:
            continue
        if "dayon.jar" not in line:
            continue
        parts = line.split(None, 1)
        try:
            pids.append(int(parts[0]))
        except ValueError:
            pass
    return pids


def stop_ours():
    pids = list_our_pids()
    if not pids:
        print("没有运行中的本项目 Dayon 进程")
        return
    print("结束进程: {}".format(pids))
    for pid in pids:
        try:
            os.kill(pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
    time.sleep(0.8)
    for pid in list_our_pids():
        try:
            os.kill(pid, signal.SIGKILL)
        except ProcessLookupError:
            pass


def uninstall():
    """干净卸载：只杀本运行时进程 + 删 .runtime/dayon，不碰 ~/.dayon / 桌面 / 系统路径。"""
    print("== 卸载 Dayon（隔离运行时） ==")
    stop_ours()
    runtime = abs_under_root(RUNTIME_ROOT)
    if os.path.isdir(runtime):
        import shutil

        shutil.rmtree(runtime, ignore_errors=True)
        print("已删除: {}".format(runtime))
    else:
        print("无需删除（不存在）: {}".format(runtime))
    # 安全检查：我们绝不应写入真实家目录
    real_dayon = os.path.expanduser("~/.dayon")
    print("未触碰用户目录 {}（若你以前装过官方 Dayon，那是你自己的数据）".format(real_dayon))
    print("== 卸载完成 ==")


def run_role(role, conf):
    ensure_display()
    extract_app()
    host = conf.get("host", "127.0.0.1")
    port = conf.get("port", "8080")
    if role == "assisted":
        write_assisted_yaml(host, port)
    else:
        write_assistant_prefs(port, conf.get("auto_accept", "1"))

    cmd = build_cmd(role, host, port)
    print("启动 {}: {}".format(role, " ".join(cmd)))
    if role == "assistant":
        print("提示: 帮助者窗口打开后点一次「开始/播放」开始监听；autoAccept 已预置。")
        print("小白侧将连到 {}:{}".format(host, port))
    else:
        print("小白侧将自动连接 {}:{}".format(host, port))

    # 前台跑，Ctrl+C 结束；文件仍保留（默认 keep）
    try:
        subprocess.run(cmd, cwd=abs_under_root(APP_DIR))
    except KeyboardInterrupt:
        print("\n已中断（运行时文件保留，下次可直接再用）")


def keep_only():
    """只准备好运行时，不启动 —— 方便下次秒开。"""
    extract_app()
    conf = read_conf()
    write_assisted_yaml(conf.get("host", "127.0.0.1"), conf.get("port", "8080"))
    write_assistant_prefs(conf.get("port", "8080"), conf.get("auto_accept", "1"))
    print("已保留运行时: {}".format(abs_under_root(RUNTIME_ROOT)))
    print("下次: python3 deploy/dayon/install.py  或  python3 deploy/dayon/install.py assistant")


def main():
    ensure_linux()
    parser = argparse.ArgumentParser(
        description="Dayon Linux：无感接入 / 保留复用 / 干净卸载（隔离 .runtime/dayon）"
    )
    parser.add_argument(
        "role",
        nargs="?",
        choices=["assisted", "assistant"],
        help="覆盖 conf 里的 role",
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="杀掉本项目 Dayon 并删除 .runtime/dayon（不碰系统/用户 ~/.dayon）",
    )
    parser.add_argument(
        "--keep",
        action="store_true",
        help="只解压并写好配置，不启动（保留供下次使用）",
    )
    parser.add_argument(
        "--stop",
        action="store_true",
        help="只结束本项目 Dayon 进程，保留文件",
    )
    args = parser.parse_args()

    if args.uninstall:
        uninstall()
        return
    if args.stop:
        stop_ours()
        return
    if args.keep:
        keep_only()
        return

    conf = read_conf()
    role = args.role or conf.get("role", "assisted")
    if role not in ("assisted", "assistant"):
        print("role 必须是 assisted 或 assistant")
        sys.exit(1)
    print("== Dayon {} ==".format(role))
    run_role(role, conf)


if __name__ == "__main__":
    main()
